### ISSUE TITLE
Добавить Netlify ссылку

### ISSUE THREAD

**Issue by elaman** [Azimbai03/burger-builder#1]
Сейчас ее нету

**Comment by Azimbai03** [comment]
Агай                                                                                                                                                                             Netlify говорит что  Не удалось развернуть сайт

**Comment by elaman** [comment]
Я на уроках показывал что делать, если netlify не работает. Пересматривай записи или слушай на урока внимательнее.

**Comment by Azimbai03** [comment]
ok

**Comment by Azimbai03** [comment]
Агай я добавил Ссылку
